#!/usr/bin/env python3
"""
Receive USRP IQ, detect transmitted WiFi Beacon PPDUs, and save CSI.

This receiver is designed for the beacon waveform generated by tx_wifi_beacon_usrp.py.
It extracts CSI from the L-LTF and stores H5/CSV/metadata datasets.

It also writes an online JSON state file for live monitoring.
"""

from __future__ import annotations

import argparse
import sys
import time

import numpy as np

try:
    import uhd
except ImportError:
    uhd = None

try:
    from .wifi_csi import extract_all_csi
    from .wifi_dataset_io import WifiCsiDatasetWriter, WifiCsiSessionMeta, utc_session_id
    from .wifi_legacy_ofdm import SAMPLE_RATE
    from .wifi_live_json import atomic_write_json, utc_now_iso
except ImportError:
    from wifi_csi import extract_all_csi
    from wifi_dataset_io import WifiCsiDatasetWriter, WifiCsiSessionMeta, utc_session_id
    from wifi_legacy_ofdm import SAMPLE_RATE
    from wifi_live_json import atomic_write_json, utc_now_iso


def build_usrp_args(serial: str) -> str:
    return f"serial={serial}" if serial else ""


def write_rx_state(path: str, payload: dict) -> None:
    if not path:
        return

    atomic_write_json(path, payload)


def main() -> None:
    p = argparse.ArgumentParser()

    p.add_argument("--serial", default="")
    p.add_argument("--freq", type=float, default=2.412e9)
    p.add_argument("--rate", type=float, default=SAMPLE_RATE)
    p.add_argument("--gain", type=float, default=35.0)
    p.add_argument("--channel", type=int, default=0)
    p.add_argument("--antenna", default="")

    p.add_argument("--duration-sec", type=float, default=30.0)
    p.add_argument("--block-ms", type=float, default=50.0)
    p.add_argument("--min-metric", type=float, default=0.35)
    p.add_argument("--min-separation-ms", type=float, default=20.0)

    p.add_argument("--label", default="empty")
    p.add_argument("--scene", default="static")
    p.add_argument("--ssid-filter", default="SENSING_WIFI")
    p.add_argument("--bssid-filter", default="02:11:22:33:44:55")
    p.add_argument("--wifi-channel", type=int, default=1)
    p.add_argument("--beacon-interval-tu", type=int, default=98)
    p.add_argument("--tx-period-ms", type=float, default=100.0)
    p.add_argument("--output-root", default="data/wifi_csi_datasets")
    p.add_argument("--notes", default="")

    p.add_argument("--local-json", default="results/wifi_online/live_wifi_rx_state.json")
    p.add_argument("--flush-every-packets", type=int, default=20)
    p.add_argument("--heartbeat-sec", type=float, default=1.0)

    args = p.parse_args()

    if abs(args.rate - SAMPLE_RATE) > 1:
        raise SystemExit("This first implementation expects --rate 20e6.")

    if uhd is None:
        raise SystemExit("Python package 'uhd' is not available. Activate .venv_uhd or install UHD Python bindings.")

    session_id = utc_session_id(args.label, args.scene)

    meta = WifiCsiSessionMeta(
        session_id=session_id,
        label=args.label,
        scene=args.scene,
        ssid_filter=args.ssid_filter,
        bssid_filter=args.bssid_filter,
        freq_hz=args.freq,
        sample_rate_hz=args.rate,
        gain_db=args.gain,
        channel=args.wifi_channel,
        beacon_interval_tu=args.beacon_interval_tu,
        tx_period_ms=args.tx_period_ms,
        notes=args.notes,
    )

    writer = WifiCsiDatasetWriter(args.output_root, meta)

    base_state = {
        "schema_version": "wifi_beacon_rx_v1",
        "role": "rx",
        "valid": True,
        "error": None,
        "status": "initializing",
        "session_id": session_id,
        "label": args.label,
        "scene": args.scene,
        "ssid_filter": args.ssid_filter,
        "bssid_filter": args.bssid_filter,
        "freq_hz": args.freq,
        "sample_rate_hz": args.rate,
        "gain_db": args.gain,
        "wifi_channel": args.wifi_channel,
        "beacon_interval_tu": args.beacon_interval_tu,
        "tx_period_ms": args.tx_period_ms,
        "output_dir": str(writer.session_dir),
        "h5_path": str(writer.h5_path),
        "csv_path": str(writer.csv_path),
        "metadata_path": str(writer.meta_path),
    }

    write_rx_state(args.local_json, {
        **base_state,
        "timestamp_utc": utc_now_iso(),
        "packets_detected": 0,
    })

    print("WiFi Beacon CSI RX configuration")
    print(f"  session: {session_id}")
    print(f"  output: {writer.session_dir}")
    print(f"  freq: {args.freq}")
    print(f"  rate: {args.rate}")
    print(f"  gain: {args.gain}")
    print(f"  duration: {args.duration_sec} s")
    print(f"  min_metric: {args.min_metric}")
    print(f"  online JSON: {args.local_json}")

    usrp = uhd.usrp.MultiUSRP(build_usrp_args(args.serial))
    usrp.set_rx_rate(args.rate, args.channel)
    usrp.set_rx_freq(uhd.types.TuneRequest(args.freq), args.channel)
    usrp.set_rx_gain(args.gain, args.channel)

    if args.antenna:
        usrp.set_rx_antenna(args.antenna, args.channel)

    usrp.set_time_now(uhd.types.TimeSpec(0.0))
    time.sleep(0.1)

    stream_args = uhd.usrp.StreamArgs("fc32", "sc16")
    stream_args.channels = [args.channel]
    rx_streamer = usrp.get_rx_stream(stream_args)

    block_samps = int(round(args.block_ms * 1e-3 * args.rate))
    block_samps = max(block_samps, int(0.01 * args.rate))

    recv_buff = np.zeros(block_samps, dtype=np.complex64)
    md = uhd.types.RXMetadata()

    cmd = uhd.types.StreamCMD(uhd.types.StreamMode.start_cont)
    cmd.stream_now = True
    rx_streamer.issue_stream_cmd(cmd)

    overlap_len = int(0.01 * args.rate)
    overlap = np.zeros(0, dtype=np.complex64)

    min_sep = int(round(args.min_separation_ms * 1e-3 * args.rate))
    packet_count = 0
    block_count = 0
    rx_error_count = 0
    last_packet_state = None
    last_heartbeat = 0.0
    last_flush_packet_count = 0
    t_start = time.time()
    t_end = t_start + args.duration_sec
    final_error = None

    try:
        while time.time() < t_end:
            n = rx_streamer.recv(recv_buff, md, timeout=2.0)
            block_count += 1

            if md.error_code != uhd.types.RXMetadataErrorCode.none:
                rx_error_count += 1
                print(f"RX metadata error: {md.strerror()}", file=sys.stderr)

                write_rx_state(args.local_json, {
                    **base_state,
                    "timestamp_utc": utc_now_iso(),
                    "status": "rx_metadata_error",
                    "packets_detected": packet_count,
                    "blocks_processed": block_count,
                    "rx_error_count": rx_error_count,
                    "last_error": md.strerror(),
                    "last_packet": last_packet_state,
                })
                continue

            if n <= 0:
                continue

            block = recv_buff[:n].copy()

            try:
                usrp_time = md.time_spec.get_real_secs()
            except Exception:
                usrp_time = usrp.get_time_now().get_real_secs()

            timestamp_unix_block = time.time()

            search = np.concatenate([overlap, block])

            results = extract_all_csi(
                search,
                sample_rate=args.rate,
                min_metric=args.min_metric,
                min_separation_samples=min_sep,
            )

            for r in results:
                if r.offset < len(overlap) - 400:
                    continue

                rel_offset_in_block = r.offset - len(overlap)

                timestamp_usrp_rx = usrp_time + max(rel_offset_in_block, 0) / args.rate
                timestamp_unix = timestamp_unix_block + max(rel_offset_in_block, 0) / args.rate

                writer.append(
                    csi=r.csi,
                    timestamp_unix=timestamp_unix,
                    timestamp_usrp_rx=timestamp_usrp_rx,
                    packet_index=packet_count,
                    timing_offset_samples=int(r.offset),
                    cfo_hz=float(r.cfo_hz),
                    ltf_metric=float(r.metric),
                    rx_power_db=float(r.rx_power_db),
                )

                last_packet_state = {
                    "packet_index": packet_count,
                    "timestamp_unix": timestamp_unix,
                    "timestamp_usrp_rx": timestamp_usrp_rx,
                    "timing_offset_samples": int(r.offset),
                    "cfo_hz": float(r.cfo_hz),
                    "ltf_metric": float(r.metric),
                    "rx_power_db": float(r.rx_power_db),
                    "csi_shape": list(r.csi.shape),
                }

                packet_count += 1

                if packet_count % 10 == 0:
                    print(
                        f"packets={packet_count} "
                        f"metric={r.metric:.3f} "
                        f"cfo={r.cfo_hz:.1f} Hz "
                        f"rx_power={r.rx_power_db:.1f} dB"
                    )

                write_rx_state(args.local_json, {
                    **base_state,
                    "timestamp_utc": utc_now_iso(),
                    "status": "receiving",
                    "packets_detected": packet_count,
                    "blocks_processed": block_count,
                    "rx_error_count": rx_error_count,
                    "last_packet": last_packet_state,
                    "elapsed_sec": time.time() - t_start,
                })

            if (
                args.flush_every_packets > 0
                and packet_count > 0
                and packet_count - last_flush_packet_count >= args.flush_every_packets
            ):
                writer.flush()
                last_flush_packet_count = packet_count

            now = time.time()
            if now - last_heartbeat >= args.heartbeat_sec:
                write_rx_state(args.local_json, {
                    **base_state,
                    "timestamp_utc": utc_now_iso(),
                    "status": "receiving",
                    "packets_detected": packet_count,
                    "blocks_processed": block_count,
                    "rx_error_count": rx_error_count,
                    "last_packet": last_packet_state,
                    "elapsed_sec": now - t_start,
                })
                last_heartbeat = now

            if len(search) > overlap_len:
                overlap = search[-overlap_len:].copy()
            else:
                overlap = search.copy()

    except KeyboardInterrupt:
        print("\nInterrupted by user.")
        final_error = "KeyboardInterrupt"

    except Exception as e:
        final_error = repr(e)
        write_rx_state(args.local_json, {
            **base_state,
            "timestamp_utc": utc_now_iso(),
            "status": "error",
            "valid": False,
            "error": final_error,
            "packets_detected": packet_count,
            "blocks_processed": block_count,
            "rx_error_count": rx_error_count,
            "last_packet": last_packet_state,
        })
        raise

    finally:
        stop_cmd = uhd.types.StreamCMD(uhd.types.StreamMode.stop_cont)
        rx_streamer.issue_stream_cmd(stop_cmd)

        writer.close()

        write_rx_state(args.local_json, {
            **base_state,
            "timestamp_utc": utc_now_iso(),
            "status": "stopped",
            "valid": final_error is None or final_error == "KeyboardInterrupt",
            "error": final_error,
            "packets_detected": packet_count,
            "blocks_processed": block_count,
            "rx_error_count": rx_error_count,
            "last_packet": last_packet_state,
            "elapsed_sec": time.time() - t_start,
        })

        print(f"Saved {packet_count} CSI packets")
        print(f"H5: {writer.h5_path}")
        print(f"CSV: {writer.csv_path}")
        print(f"Metadata: {writer.meta_path}")
        print(f"Online JSON: {args.local_json}")


if __name__ == "__main__":
    main()
