#!/usr/bin/env python3
"""
Offline processor for DMG/802.11bf-inspired sensing RAW captures.

Input:
    raw IQ .npy captured at 20 Msps
    DMG-like waveform .npz generated by waveform.py / tx_dmg_sensing_usrp.py

Processing:
    1. Coarse energy seeds
    2. CEF Golay matched-correlation timing refinement
    3. Burst timing estimation
    4. CIR extraction using complementary Golay CEF
    5. Optional CFR computation by FFT(CIR)

This is the first offline RX validation step before implementing the live RX.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from waveform import load_dmg_sensing_waveform_npz


def db10(x: np.ndarray | float) -> np.ndarray | float:
    return 10.0 * np.log10(np.asarray(x) + 1e-12)


def greedy_energy_seeds(
    x: np.ndarray,
    fs: float,
    expected: int,
    energy_win_ms: float,
    min_sep_ms: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Coarse energy candidate selection.

    Returns:
        seed_samples
        pwr_db per energy window
        selected_window_indices
    """
    win = int(round(energy_win_ms * 1e-3 * fs))
    if win <= 0:
        raise ValueError("energy window too small")

    nwin = len(x) // win

    pwr = np.empty(nwin, dtype=np.float32)

    for i in range(nwin):
        b = x[i * win : (i + 1) * win]
        pwr[i] = np.mean(np.abs(b) ** 2)

    pwr_db = db10(pwr).astype(np.float32)

    guard_windows = max(1, int(round(min_sep_ms / energy_win_ms)))

    score = pwr_db.copy()

    selected = []

    for _ in range(expected):
        idx = int(np.argmax(score))
        val = float(score[idx])

        if not np.isfinite(val):
            break

        selected.append(idx)

        a = max(0, idx - guard_windows)
        b = min(len(score), idx + guard_windows + 1)
        score[a:b] = -np.inf

    selected = np.array(sorted(selected), dtype=np.int64)

    seed_samples = selected * win

    return seed_samples.astype(np.int64), pwr_db, selected


def corr_valid(x: np.ndarray, seq: np.ndarray) -> np.ndarray:
    """
    Complex valid correlation against known sequence.

    np.correlate(a, v, mode='valid') computes:
        sum a[n+k] * conj(v[k])

    seq is real/complex known training.
    """
    return np.correlate(x, seq.astype(np.complex64), mode="valid")


def refine_with_cef(
    x: np.ndarray,
    seed_sample: int,
    cef_ga: np.ndarray,
    cef_gb: np.ndarray,
    cef_start: int,
    cef_stop: int,
    waveform_len: int,
    fs: float,
    search_before_ms: float,
    search_after_ms: float,
) -> dict[str, Any] | None:
    """
    Refine burst start around a coarse energy seed using CEF A/B correlation.

    The seed usually lands somewhere inside a high-energy part of the burst.
    Therefore, possible burst_start is searched in:
        seed - search_before_ms ... seed + search_after_ms

    Score for candidate burst_start s:
        |corr(rx[s+cef_start : s+cef_start+len(A)], A)|^2
      + |corr(rx[s+cef_start+len(A) : s+cef_start+len(A)+len(B)], B)|^2

    This uses the CEF field, which is designed for channel estimation.
    """
    la = len(cef_ga)
    lb = len(cef_gb)

    assert la == lb

    search_before = int(round(search_before_ms * 1e-3 * fs))
    search_after = int(round(search_after_ms * 1e-3 * fs))

    start_min = int(seed_sample - search_before)
    start_max = int(seed_sample + search_after)

    start_min = max(0, start_min)
    start_max = min(len(x) - waveform_len - 1, start_max)

    if start_max <= start_min:
        return None

    # Need segment covering all possible CEF A/B positions.
    seg_start = start_min + cef_start
    seg_stop = start_max + cef_start + la + lb

    if seg_start < 0 or seg_stop > len(x):
        return None

    seg = np.asarray(x[seg_start:seg_stop], dtype=np.complex64)

    corr_a = corr_valid(seg, cef_ga.astype(np.complex64))
    corr_b = corr_valid(seg, cef_gb.astype(np.complex64))

    # For a candidate burst_start = start_min + k:
    # A starts at seg offset k
    # B starts at seg offset k + la
    num_candidates = start_max - start_min

    if len(corr_a) < num_candidates or len(corr_b) < num_candidates + la:
        return None

    ca = corr_a[:num_candidates]
    cb = corr_b[la : la + num_candidates]

    score = np.abs(ca) ** 2 + np.abs(cb) ** 2

    # Normalize by local received energy and sequence energy.
    # This makes the metric more comparable between bursts.
    # Fast local energy using cumulative sum instead of a Python loop.
    #
    # For each candidate k, the CEF window is:
    #     seg[k : k + la + lb]
    #
    # The old implementation computed np.mean() inside a loop over all
    # candidates. With large search windows this becomes extremely slow.
    # Cumulative sum makes it O(N) vectorized.
    win_len = la + lb
    pwr = np.abs(seg) ** 2
    cs = np.concatenate([
        np.array([0.0], dtype=np.float64),
        np.cumsum(pwr.astype(np.float64)),
    ])

    sums = cs[win_len : win_len + num_candidates] - cs[:num_candidates]
    local_energy = (sums / float(win_len) + 1e-12).astype(np.float32)

    seq_energy = float(np.sum(np.abs(cef_ga) ** 2) + np.sum(np.abs(cef_gb) ** 2))
    metric = score / (local_energy * seq_energy * seq_energy + 1e-12)

    best_k = int(np.argmax(metric))
    best_start = int(start_min + best_k)

    rx_power = float(np.mean(np.abs(x[best_start : best_start + waveform_len]) ** 2))

    return {
        "seed_sample": int(seed_sample),
        "start_sample": int(best_start),
        "metric": float(metric[best_k]),
        "raw_score": float(score[best_k]),
        "cef_power_db": float(db10(local_energy[best_k])),
        "burst_power_db": float(db10(rx_power)),
        "search_start_min": int(start_min),
        "search_start_max": int(start_max),
    }


def extract_cir_from_cef(
    x: np.ndarray,
    start_sample: int,
    cef_ga: np.ndarray,
    cef_gb: np.ndarray,
    cef_start: int,
) -> np.ndarray:
    """
    Estimate CIR from CEF using complementary Golay correlation.

    Exact-window simple estimator:
        CIR = corr(rx_A, A) + corr(rx_B, B)

    Output length:
        2 * len(cef_ga) - 1

    Center tap is at index len(cef_ga)-1.
    """
    la = len(cef_ga)

    a0 = start_sample + cef_start
    b0 = a0 + la

    rx_a = np.asarray(x[a0 : a0 + la], dtype=np.complex64)
    rx_b = np.asarray(x[b0 : b0 + la], dtype=np.complex64)

    if len(rx_a) != la or len(rx_b) != la:
        raise ValueError("CEF extraction window out of range")

    ca = np.correlate(rx_a, cef_ga.astype(np.complex64), mode="full")
    cb = np.correlate(rx_b, cef_gb.astype(np.complex64), mode="full")

    cir = (ca + cb) / (2.0 * la)

    return cir.astype(np.complex64)


def deduplicate_detections(
    detections: list[dict[str, Any]],
    min_sep_samples: int,
) -> list[dict[str, Any]]:
    """
    Remove detections that refined to almost the same burst.
    Keep the highest metric one.
    """
    if not detections:
        return []

    dets = sorted(detections, key=lambda d: d["metric"], reverse=True)

    kept: list[dict[str, Any]] = []

    for d in dets:
        s = int(d["start_sample"])

        if all(abs(s - int(k["start_sample"])) >= min_sep_samples for k in kept):
            kept.append(d)

    kept = sorted(kept, key=lambda d: d["start_sample"])

    return kept


def main() -> None:
    p = argparse.ArgumentParser()

    p.add_argument("--input-npy", required=True)
    p.add_argument(
        "--waveform-npz",
        default="results/wlan_sensing_dmg/dmg_like_sensing_ppdu_v1.npz",
    )
    p.add_argument(
        "--output-npz",
        default="results/wlan_sensing_dmg/raw_dmg_like_tx_5s_processed.npz",
    )
    p.add_argument(
        "--output-csv",
        default="results/wlan_sensing_dmg/raw_dmg_like_tx_5s_detections.csv",
    )

    p.add_argument("--rate", type=float, default=20e6)
    p.add_argument("--tx-period-ms", type=float, default=100.0)

    p.add_argument("--energy-win-ms", type=float, default=1.0)
    p.add_argument("--energy-min-sep-ms", type=float, default=70.0)

    p.add_argument("--search-before-ms", type=float, default=3.0)
    p.add_argument("--search-after-ms", type=float, default=1.5)

    p.add_argument("--dedup-min-sep-ms", type=float, default=50.0)
    p.add_argument("--expected-bursts", type=int, default=0)
    p.add_argument("--extra-seeds", type=int, default=20)

    p.add_argument("--min-metric", type=float, default=0.0)

    args = p.parse_args()

    x = np.load(args.input_npy, mmap_mode="r")
    n = len(x)
    duration_s = n / args.rate

    wf = load_dmg_sensing_waveform_npz(args.waveform_npz)
    meta = wf["metadata"]
    field_map = meta["field_map"]

    waveform_len = int(meta["waveform_samples"])
    cef_start = int(field_map["cef"]["start"])
    cef_stop = int(field_map["cef"]["stop"])

    cef_ga = wf["cef_ga"].astype(np.float32)
    cef_gb = wf["cef_gb"].astype(np.float32)

    if args.expected_bursts > 0:
        expected = args.expected_bursts
    else:
        expected = int(round(duration_s / (args.tx_period_ms / 1000.0)))

    seed_count = expected + max(0, args.extra_seeds)

    print("DMG-like RAW offline processor")
    print(f"  input: {args.input_npy}")
    print(f"  waveform: {args.waveform_npz}")
    print(f"  samples: {n}")
    print(f"  duration_s: {duration_s:.6f}")
    print(f"  expected bursts: {expected}")
    print(f"  seed count: {seed_count}")
    print(f"  waveform samples: {waveform_len}")
    print(f"  CEF start/stop: {cef_start}/{cef_stop}")
    print(f"  CEF Golay len: {len(cef_ga)}")

    seed_samples, energy_pwr_db, selected_windows = greedy_energy_seeds(
        x=x,
        fs=args.rate,
        expected=seed_count,
        energy_win_ms=args.energy_win_ms,
        min_sep_ms=args.energy_min_sep_ms,
    )

    print(f"  coarse seeds: {len(seed_samples)}")

    raw_detections: list[dict[str, Any]] = []

    for i, seed in enumerate(seed_samples):
        d = refine_with_cef(
            x=x,
            seed_sample=int(seed),
            cef_ga=cef_ga,
            cef_gb=cef_gb,
            cef_start=cef_start,
            cef_stop=cef_stop,
            waveform_len=waveform_len,
            fs=args.rate,
            search_before_ms=args.search_before_ms,
            search_after_ms=args.search_after_ms,
        )

        if d is None:
            continue

        d["coarse_index"] = int(i)

        if float(d["metric"]) >= args.min_metric:
            raw_detections.append(d)

    dedup_min_sep_samples = int(round(args.dedup_min_sep_ms * 1e-3 * args.rate))

    detections = deduplicate_detections(
        raw_detections,
        min_sep_samples=dedup_min_sep_samples,
    )

    # Keep strongest expected detections if we have too many.
    if len(detections) > expected:
        detections = sorted(detections, key=lambda d: d["metric"], reverse=True)[:expected]
        detections = sorted(detections, key=lambda d: d["start_sample"])

    print(f"  raw refined detections: {len(raw_detections)}")
    print(f"  deduplicated detections: {len(detections)}")

    if not detections:
        raise SystemExit("No detections found.")

    start_samples = np.array([d["start_sample"] for d in detections], dtype=np.int64)
    seed_samples_out = np.array([d["seed_sample"] for d in detections], dtype=np.int64)
    metrics = np.array([d["metric"] for d in detections], dtype=np.float32)
    raw_scores = np.array([d["raw_score"] for d in detections], dtype=np.float32)
    burst_power_db = np.array([d["burst_power_db"] for d in detections], dtype=np.float32)
    cef_power_db = np.array([d["cef_power_db"] for d in detections], dtype=np.float32)

    times_s = start_samples / args.rate

    cirs = []

    for s in start_samples:
        cirs.append(
            extract_cir_from_cef(
                x=x,
                start_sample=int(s),
                cef_ga=cef_ga,
                cef_gb=cef_gb,
                cef_start=cef_start,
            )
        )

    cirs = np.stack(cirs, axis=0).astype(np.complex64)

    # CFR from CIR. Use 1024-point FFT for a stable frequency-domain feature.
    cfr = np.fft.fftshift(np.fft.fft(cirs, n=1024, axis=1), axes=1).astype(np.complex64)

    periods = np.diff(times_s)

    print("Detection summary")
    print(f"  detections: {len(detections)}")
    print(f"  first times s: {times_s[:20]}")

    if len(periods) > 0:
        print(f"  period mean s: {float(np.mean(periods)):.9f}")
        print(f"  period std s: {float(np.std(periods)):.9f}")
        print(f"  first periods s: {periods[:20]}")

    print(f"  metric mean: {float(np.mean(metrics)):.6e}")
    print(f"  metric min/max: {float(np.min(metrics)):.6e} / {float(np.max(metrics)):.6e}")
    print(f"  burst power dB mean: {float(np.mean(burst_power_db)):.3f}")
    print(f"  burst power dB min/max: {float(np.min(burst_power_db)):.3f} / {float(np.max(burst_power_db)):.3f}")
    print(f"  CIR shape: {cirs.shape}")
    print(f"  CFR shape: {cfr.shape}")

    out = Path(args.output_npz)
    out.parent.mkdir(parents=True, exist_ok=True)

    result_meta = {
        "schema_version": "dmg_like_raw_offline_processing_v1",
        "input_npy": args.input_npy,
        "waveform_npz": args.waveform_npz,
        "sample_rate_hz": args.rate,
        "duration_s": duration_s,
        "tx_period_ms": args.tx_period_ms,
        "expected_bursts": expected,
        "detections": int(len(detections)),
        "waveform_metadata": meta,
        "processing_args": vars(args),
    }

    np.savez_compressed(
        out,
        start_samples=start_samples,
        seed_samples=seed_samples_out,
        times_s=times_s.astype(np.float64),
        metrics=metrics,
        raw_scores=raw_scores,
        burst_power_db=burst_power_db,
        cef_power_db=cef_power_db,
        cir=cirs,
        cfr=cfr,
        metadata_json=json.dumps(result_meta, indent=2),
    )

    csv_path = Path(args.output_csv)
    csv_path.parent.mkdir(parents=True, exist_ok=True)

    with csv_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "idx",
            "time_s",
            "start_sample",
            "seed_sample",
            "metric",
            "raw_score",
            "burst_power_db",
            "cef_power_db",
        ])

        for i, d in enumerate(detections):
            w.writerow([
                i,
                f"{times_s[i]:.9f}",
                int(start_samples[i]),
                int(seed_samples_out[i]),
                f"{metrics[i]:.9e}",
                f"{raw_scores[i]:.9e}",
                f"{burst_power_db[i]:.6f}",
                f"{cef_power_db[i]:.6f}",
            ])

    print(f"Saved NPZ: {out}")
    print(f"Saved CSV: {csv_path}")


if __name__ == "__main__":
    main()
